package org.usfirst.frc3617.InsertMemeHere;


//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.Victor;
import edu.wpi.first.wpilibj.buttons.JoystickButton;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS




	import edu.wpi.first.wpilibj.GenericHID;
	import edu.wpi.first.wpilibj.Joystick;
	import edu.wpi.first.wpilibj.Spark;
	import edu.wpi.first.wpilibj.Victor;
	import edu.wpi.first.wpilibj.buttons.*;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
	import edu.wpi.first.wpilibj.livewindow.LiveWindow;

	/**
	 * The RobotMap is a mapping from the ports sensors and actuators are wired into
	 * to a variable name. This provides flexibility changing wiring, makes checking
	 * the wiring easier and significantly reduces the number of magic numbers
	 * floating around.
	 */
	@SuppressWarnings("unused")
	public class RobotMap {

		//Start the real stuff
	    public static Joystick driveStick = new Joystick(0);
		public static Joystick gunnerStick = new Joystick(1);
		public static int frontRightMotor = 1;
		public static int frontLeftMotor = 0;
		public static int rearLeftMotor = 2;
		public static int rearRightMotor = 3;
		public static int armMotor = 5;
		public static int climbMotor = 4;
		public static int clawMotor = 6;
		public static int extendMotor=7;
	
		
		public static JoystickButton clawGrab = new JoystickButton(gunnerStick, 1); 
		public static JoystickButton clawOut = new JoystickButton(gunnerStick, 2); 
		public static JoystickButton armOut = new JoystickButton(gunnerStick, 11);
		public static JoystickButton armIn = new JoystickButton(gunnerStick, 12);
		public static Spark armExtend = new Spark(extendMotor);
		public static Spark arm = new Spark(armMotor);
		public static Victor climber =new Victor(climbMotor);
		public static Spark claw = new Spark(clawMotor);
		public static void init() {
	        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

	    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	    	//More real stuff
	    }
	    
	
    }
